### ISSUE TITLE
Bot didn't greet when joining server

### ISSUE THREAD

**Issue by ineffyble** [silasary/iwazaru_bot#1]
Iwazaru was invited to my server and joined, but didn't say anything - I noticed the last commit removed the `pass` at the end of the relevant block, could that be it?

**Comment by silasary** [comment]
`pass` is a no-op command.  It literally exists to be the equivelent of `{ }`.

The most likely situation is that the default channel of your server is protected in some way, and the bot doesn't have permission to speak there.

**Comment by ineffyble** [comment]
hmm, I really don't think that's it, might try and test

**Comment by silasary** [comment]
So the default channel is the top channel in the list.  It's not necessarily the channel that new users would be welcomed in, or one that the bot has permission to talk in.
