### ISSUE TITLE
Does not display explanation for certain warning

### ISSUE THREAD

**Issue by mastercoms** [silasary/iwazaru_bot#181]
![image](https://user-images.githubusercontent.com/2672245/141145540-2a70c04d-9f67-401c-8568-dcc55f26e88f.png)

https://github.com/silasary/iwazaru_bot/blob/ff925ef03b49bb951f79fb88f8f787f73a9bd8ba/discordbot/warnings.py#L21

none display from this line

**Comment by silasary** [comment]
Not sure what was happening there, but rebooting the bot seems to have fixed it.
![image](https://user-images.githubusercontent.com/194254/141216873-0080e9d9-a3d5-4b5f-b7ef-7e1accb4f1a0.png)
