### ISSUE TITLE
Does not work on threads

### ISSUE THREAD

**Issue by mastercoms** [silasary/iwazaru_bot#182]
![image](https://user-images.githubusercontent.com/2672245/141517416-10443996-e2b9-44fb-8b33-d3ed4cf3170c.png)

Someone in my server discovered that even though the bot is in the thread, it does not react to the messages

**Comment by silasary** [comment]
I'm working on it.

Unfortunately, discord.py was never updated to support Gateway version v9 (and is now [unsupported](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1)), so I'm in the process of porting my bots to a new [API wrapper](https://github.com/Discord-Snake-Pit/Dis-Snek).  While Iwazaru is a simple bot, and shouldn't be too complex, it's still a bit of a process

**Comment by mastercoms** [comment]
Awesome, thank you!

**Comment by silasary** [comment]
Okay, the port is completed, and is now live.  Let me know if you see any weird behavior or bugs :)

**Comment by mastercoms** [comment]
Works, thanks!
